Added git installation
appwrite/docker-base pull request #10
Opened 2023-04-25 11:14 UTC by vermakhushboo

## What does this PR do?

Added git installation in docker base

## Related PRs and Issues

https://github.com/appwrite/appwrite/pull/5322

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?

Yes

2023-04-25 11:22 UTC, vermakhushboo commented on Dockerfile
> +
Updated, please re-review :)

2023-04-25 12:20 UTC, eldadfux requested changes

2023-04-25 12:20 UTC, eldadfux commented on Dockerfile
> +  git
```suggestion
  git \
```

2023-04-26 05:40 UTC, lohanidamodar reviewed
LGTM, just that build is failing ?

2023-04-28 05:54 UTC, eldadfux approved these changes

2023-04-28 05:54 UTC, merged